### ISSUE TITLE
q to quit

### ISSUE THREAD

**Issue by JohnAlexCO** [Soviet-Linux/revolution-installer#3]
Entering `q` to quit the installer does not yield expected result. Prompt appears again, and the program seg-faults after entering again. Dump
```
=== Disk Partition ===
Enter a disk to edit (q to quit, l to list disks): l
/dev/sda1
/dev/sda
/dev/nvme0n1p1
/dev/nvme0n1
/dev/nvme0
Enter a disk to edit (q to quit, l to list disks): q
=== File System Creation ===
Enter a partition for file system creation: (q to quit, l to list disks): q
=== Mount Setup ===
Choose the mounting point for the following partitions.
You can quit at any time by entering q.
Segmentation fault (core dumped)

```

**Comment by AntaresMKII** [comment]
Thank you for your comment. I'm aware of the segmentation fault when determining mount setup. The quitting not working as intended is working as expected , but I see that using the word quit might be misleading since quit exits the current input loop and not the program. Using terminology such as continue and `c` as input string might be a better idea. Thank you for bringing this to my attention.
